<a href="https://colab.research.google.com/github/rukundob451/MachineLearning/blob/main/Pandas_Demo2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

9th February 2023 Pandas-Demo2
From toturial 4

In [90]:
import pandas as pd

In [144]:
df = pd.read_csv('survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv('survey_results_schema.csv', index_col='Column')

In [ ]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [ ]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [ ]:
filt = df['LanguageWorkedWith'].str.contains('Python', na=False)

In [ ]:
filt

Respondent
1         True
2         True
3        False
4         True
5         True
         ...
53746    False
53747    False
53748     True
53749     True
53750    False
Name: LanguageWorkedWith, Length: 53412, dtype: bool

In [ ]:
df.loc[filt]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53738,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,New Zealand,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,100 to 499 employees,"Developer, back-end;Developer, full-stack",20,7,15,Very satisfied,Very satisfied,Very confident,Not sure,No,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles;Interview ...,No,"Industry that I'd be working in;Languages, fra...",I heard about a job opportunity (from a recrui...,NZD,New Zealand dollar,96000.0,Yearly,66211.0,40.0,There is a schedule and/or spec (made by me or...,Not enough people for the workload,Less than once per month / Never,Office,Average,"Yes, because I see value in code review",6.0,"Yes, it's part of our process",Not sure,I have little or no influence,Bash/Shell/PowerShell;Python;SQL,Python,PostgreSQL,PostgreSQL,Docker;Linux,Docker;Linux,Django,Django,Ansible,NaN,IntelliJ,Linux-based,Development;Testing;Production;Outside of work...,Not at all,NaN,Yes,Yes,Yes,I don't use social media,In real life (in person),Username,2009,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Daily or almost daily,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Somewhat less welcome now than last year,NaN,39.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
53739,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Ghana,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,500 to 999 employees,"Developer, back-end;Developer, full-stack;Engi...",8,18,6,Very satisfied,Slightly satisfied,Somewhat confident,No,Yes,"I’m not actively looking, but I am open to new...",1-2 years ago,Complete a take-home project;Interview with pe...,No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,GHS,Ghanaian cedi,15000.0,Monthly,36072.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Lack of support f...,All or almost all the time (I'm full-time remote),Home,Far above average,"Yes, because I see value in code review",6.0,"Yes, it's not part of our process but the deve...",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;Go;JavaScript;PHP;Python...,Go;JavaScript;Python,DynamoDB;Elasticsearch;Firebase;MongoDB;MySQL;...,Elasticsearch;MongoDB;PostgreSQL;Redis,AWS;Docker;Google Cloud Platform;Heroku;Kubern...,Docker;Google Cloud Platform;Kubernetes;Slack,Angular/Angular.js;Django;Express;Flask;jQuery...,Django;Flask;React.js,Node.js;Pandas;React Native;TensorFlow,Apache Spark;Hadoop;Pandas;React Native;Tensor...,IPython / Jupyter;PyCharm;Sublime Text;Visual ...,MacOS,Production,Not at all,A passing fad,Yes,Yes,Yes,Instagram,Online,Username,2011,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Black or of African descent,Yes,Too long,Easy
53741,"I am not primarily a developer, but I write co...",Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",United States,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,NaN,Data scientist or machine learning specialist,30,22,10,Slightly satisfied,NaN,NaN,NaN,NaN,I am actively looking for a job,1-2 years ago,Write any code;Complete a take-home project;In...,No,Specific department or team I'd be working on;...,I was preparing for a job search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Average,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Python;Scala;SQL,C;Go;HTML/CSS;JavaScript;Python;Rust;Scala;SQL...,MySQL,Elasticsearch;MySQL;PostgreSQL,AWS;Linux;Raspberry Pi,Arduino;AWS;Docker;Linux;Raspberry Pi,Django,Django;React.js,Apache Spark;Pandas;TensorFlow,Apache Spark;Node.js;Pandas;TensorFlow,IntelliJ;IPython / Jupyter;Vim,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,Yes,LinkedIn,Online,Username,2010,Daily or almost daily,Find answers to specific questions,3-5 times per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,NaN,60.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
53748,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Completed an industry certification program (e...,100 to 499 employees,"Developer, full-stack",12,14,8,Very satisfied,Very satisfied,Somewhat confident,Yes,Not sure,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Financial performance or funding status of the...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,425000.0,Yearly,425000.0,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,A few days each month,Office,Average,"Yes, because I see value in code review",15.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have some influence,C#;JavaScript;Python;SQL;TypeScript,C#;Go;Python;TypeScript,Microsoft SQL Server;Redis,PostgreSQL;Redis,AWS;Docker;Linux;Windows,AWS;Docker;Kubernetes;Linux,Express;Flask;React.js,Django;Flask;React.js,.NET;Node.js;Pandas,.NET Core;Pandas,IPython / Jupyter;Vim;Visual Studio;Visual Stu...,Linux-based,Development;Testing;Production;Outside of work...,NaN,An irresponsible use of resources,Yes,Yes,Yes,Reddit,Online,Username,I don't remember,Multiple times per day,Find answers to specific questions;Pass the ti...,1-2 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","No, not really",Somewhat less welcome now than last year,NaN,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
53749,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,"10,000 or more employees",Data or business analyst,33,10,23,Slightly satisfied,Slightly satisfied,Not at all confident,No,No,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,GBP,Pound sterling,50600.0,Yearly,66209.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,A little above average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,PHP;Python;SQL;VBA;Other(s):,F#;PHP;Python;R;SQL;VBA;Other(s):,Microsoft SQL Server;MySQL,Microsoft SQL Server,WordPress,WordPress,NaN,NaN,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,NaN,Yes,SIGH,Yes,Facebook,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Contribute ...,1-2 times per week,They were about the same,NaN,Yes,Daily or almost daily,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,NaN,43.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy

Toturial 5 Updating Rows and Columns

In [128]:
people = {
    "first": ["Benjamin", "Cory", "Dev", "Adam"],
    "last": ["Rukundo", "Doe", "Doe", "Joe"],
    "email": ["ben@xyz", "cory@xyz", "dev@xyz", "A@email.com"]
}

In [ ]:
dff = pd.DataFrame(people)

In [ ]:
dff

      first     last     email
0  Benjamin  Rukundo   ben@xyz
1      Cory      Doe  cory@xyz
2       Dev      Doe   dev@xyz

In [ ]:
dff.columns

Index(['first', 'last', 'email'], dtype='object')

In [ ]:
dff.columns = ['first_name', 'last_name', 'email']

In [ ]:
dff.columns

Index(['first_name', 'last_name', 'email'], dtype='object')

In [ ]:
dff

  first_name last_name     email
0   Benjamin   Rukundo   ben@xyz
1       Cory       Doe  cory@xyz
2        Dev       Doe   dev@xyz

In [ ]:
dff.columns = [x.lower() for x in dff.columns]
dff

  first_name last_name     email
0   Benjamin   Rukundo   ben@xyz
1       Cory       Doe  cory@xyz
2        Dev       Doe   dev@xyz

In [ ]:
dff.rename(columns={'first_name': 'first', 'last_name': 'last'}, inplace=True)

In [ ]:
dff

      first     last     email
0  Benjamin  Rukundo   ben@xyz
1      Cory      Doe  cory@xyz
2       Dev      Doe   dev@xyz

In [ ]:
dff.loc[2] = ['John', 'Smith', 'JohnSmith@email.com']

In [ ]:
dff

      first     last                email
0  Benjamin  Rukundo              ben@xyz
1      Cory      Doe             cory@xyz
2      John    Smith  JohnSmith@email.com

In [ ]:
dff.loc[2, ['last', 'email']] = ['Doe', 'JohnDoe@email.com']

In [ ]:
dff

      first     last              email
0  Benjamin  Rukundo            ben@xyz
1      Cory      Doe           cory@xyz
2      John      Doe  JohnDoe@email.com

In [ ]:
dff.loc[2, ['last', 'email']] = ['Augusto', 'JohnDoe@email.com']

In [ ]:
dff

      first     last              email
0  Benjamin  Rukundo            ben@xyz
1      Cory      Doe           cory@xyz
2      John  Augusto  JohnDoe@email.com

In [ ]:
dff.at[2, 'last'] = 'Doe'

In [ ]:
dff

      first     last              email
0  Benjamin  Rukundo            ben@xyz
1      Cory      Doe           cory@xyz
2      John      Doe  JohnDoe@email.com

In [ ]:
filt = (dff['email'] == 'JohnDoe@email.com')
dff.loc[filt, 'last'] = 'Smith'

In [ ]:
dff[filt]['last']

2    Doe
Name: last, dtype: object

In [ ]:
dff

      first     last              email
0  Benjamin  Rukundo            ben@xyz
1      Cory      Doe           cory@xyz
2      John    Smith  JohnDoe@email.com

In [ ]:
dff['email'] = dff['email'].str.lower()

In [ ]:
dff

      first     last              email
0  Benjamin  Rukundo            ben@xyz
1      Cory      Doe           cory@xyz
2      John    Smith  johndoe@email.com

4 methods used to change multiple rows at once
1. apply
2. map
3. applymap
4. replace

In [ ]:
dff['email'].apply(len)

0     7
1     8
2    17
Name: email, dtype: int64

In [ ]:
def update_email(email):
  return email.upper()

In [ ]:
dff['email'] = dff['email'].apply(update_email)

In [ ]:
dff

      first     last              email
0  Benjamin  Rukundo            BEN@XYZ
1      Cory      Doe           CORY@XYZ
2      John    Smith  JOHNDOE@EMAIL.COM

In [ ]:
dff['email'] = dff['email'].apply(lambda x: x.lower())

In [ ]:
dff

      first     last              email
0  Benjamin  Rukundo            ben@xyz
1      Cory      Doe           cory@xyz
2      John    Smith  johndoe@email.com

In [ ]:
dff.apply(len, axis='columns')

0    3
1    3
2    3
dtype: int64

In [ ]:
len(dff['email'])

3

In [ ]:
dff.apply(pd.Series.min)

first    Benjamin
last          Doe
email     ben@xyz
dtype: object

In [ ]:
dff.apply(lambda x: x.min())

first    Benjamin
last          Doe
email     ben@xyz
dtype: object

In [ ]:
dff.applymap(len)

   first  last  email
0      8     7      7
1      4     3      8
2      4     5     17

In [ ]:
dff.applymap(str.lower)

      first     last              email
0  benjamin  rukundo            ben@xyz
1      cory      doe           cory@xyz
2      john    smith  johndoe@email.com

In [91]:
dff['first'].map({'Benjamin': 'Chris', 'Corey': 'Mary'})

0    Chris
1      NaN
2      NaN
Name: first, dtype: object

In [92]:
dff['first'].replace({'Benjamin': 'Chris', 'Corey': 'Mary'})

0    Chris
1     Cory
2     John
Name: first, dtype: object

In [93]:
dff

      first     last              email
0  Benjamin  Rukundo            ben@xyz
1      Cory      Doe           cory@xyz
2      John    Smith  johndoe@email.com

In [95]:
df.rename(columns={'ConvertedComp': 'SalaryUSD'}, inplace=True)

In [97]:
df['SalaryUSD']

Respondent
1             NaN
2             NaN
3          8820.0
4         61000.0
5             NaN
           ...
53746     90072.0
53747    150000.0
53748    425000.0
53749     66209.0
53750     67200.0
Name: SalaryUSD, Length: 53412, dtype: float64

In [98]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
53746     No
53747     No
53748    Yes
53749    Yes
53750    Yes
Name: Hobbyist, Length: 53412, dtype: object

In [99]:
df['Hobbyist'].map({'Yes': True, 'No': False})

Respondent
1         True
2        False
3         True
4        False
5         True
         ...
53746    False
53747    False
53748     True
53749     True
53750     True
Name: Hobbyist, Length: 53412, dtype: bool

In [100]:
df['Hobbyist'] = df['Hobbyist'].map({'Yes': True, 'No': False})

In [101]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,SalaryUSD,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,True,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,False,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",True,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53746,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,South Africa,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","1,000 to 4,999 employees","Academic researcher;Developer, back-end;Develo...",31,18,28,Very satisfied,Slightly satisfied,Somewhat confident,No,I am already a manager,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in peer roles;Interview ...,No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",ZAR,South African rand,100000.0,Monthly,90072.0,45.0,There's no schedule or spec; I work on what se...,Distracting work environment;Meetings,A few days each month,Home,Average,"Yes, because I see value in code review",10.0,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,C#;SQL;Other(s):,C#;SQL,Microsoft SQL Server;Other(s):,Microsoft SQL Server,Microsoft Azure;Windows,Microsoft Azure;Windows,NaN,NaN,.NET,.NET,Visual Studio,Windows,I do not use containers,Non-currency applications of blockchain,A passing fad,No,SIGH,Yes,WhatsApp,In real life (in person),UserID,2017,Multiple times per day,Find answers to specific questions,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,51.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
53747,I am a developer by profession,False,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, back-end",23,18,20,Slightly satisfied,Slightly satisfied,Not at all confident,Yes,Yes,I am actively looking for a job,1-2 years ago,"Write code by hand (e.g., on a whiteboard);Com...",Yes,Office environment or company culture;Opportun...,I was preparing for a job search,USD,United States dollar,150000.0,Yearly,150000.0,50.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Lack of support f...,A few days each month,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have little or no influence,Kotlin,C#;Java;JavaScript;Kotlin,Microsoft SQL Server;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL,Android;AWS;Docker;Heroku;MacOS,NaN,React.js,React.js,NaN,.NET;.NET Core,Android Studio;NetBeans;RubyMine;Visual Studio...,MacOS,Testing,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,No,Yes,Yes,Twitter,In real life (in person),Username,2010,Multiple times per day,Find answers to specific questions,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers,44.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
53748,I am a developer by profession,True,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Completed an industry certification program (e...,100 to 499 employees,"Developer, full-stack",12,14,8,Very satisfied,Very satisfied,Somewhat confident,Yes,Not sure,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Financial performance or funding status of the...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,425000.0,Yearly,425000.0,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,A few days each month,Office,Average,"Yes, because I see value in code review",15.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have some influence,C#;JavaScript;Python;SQL;TypeScript,C#;Go;Python;TypeScript,Microsoft SQL Server;Redis,PostgreSQL;Redis,AWS;Docker;Linux;Windows,AWS;Docker;Kubernetes;Linux,Express;Flask;React.js,Django;Flask;React.js,.NET;Node.js;Pandas,.NET Core;Pandas,IPython / Jupyter;Vim;Visual Studio;Visual Stu...,Linux-based,Development;Testing;Production;Outside of work...,NaN,An irresponsible use of resources,Yes,Yes,Yes,Reddit,Online,Username,I don't remember,Multiple times per day,Find answers to specific questions;Pass the ti...,1-2 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","No, not really",Somewhat less welcome now than last year,NaN,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
53749,"I am not primarily a developer, but I write co...",True,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Taken an online course in programming or softw...,"10,000 or more employees",Data or business analyst,33,10,23,Slightly satisfied,Slightly satisfied,Not at all confident,No,No,"I’m not actively looking, but I am open to new...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,GBP,Pound sterling,50600.0,Yearly,66209.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,A little above average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,PHP;Python;SQL;VBA;Other(s):,F#;PHP;Python;R;SQL;VBA;Other(s):,Microsoft SQL Server;MySQL,Microsoft SQL Server,WordPress,WordPress,NaN,NaN,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,NaN,Yes,SIGH,Yes,Facebook,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Contribute ...,1-2 times per week,They were about the same,NaN,Yes,Daily or almost daily,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,NaN,43.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
53750,I am a developer by profession,True,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Turkey,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...","Taught yourself a new language, framework, or ...","5,000 to 9,999 employees",Data scientist or machine learning specialist;...,22,13,20,Very dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am actively looking for a job,1-2 years ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Remote work op...,Re-entry into the workforce,TRY,Turkish lira,7000.0,Weekly,67200.0,40.0,There's no schedule or spec; I work on what se...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Lecture 5 Add/Remove rows and columns

In [103]:
dff['first'] + ' ' + dff['last']

0    Benjamin Rukundo
1            Cory Doe
2          John Smith
dtype: object

In [104]:
dff['full_name'] = dff['first'] + ' ' + dff['last']

In [105]:
dff

      first     last              email         full_name
0  Benjamin  Rukundo            ben@xyz  Benjamin Rukundo
1      Cory      Doe           cory@xyz          Cory Doe
2      John    Smith  johndoe@email.com        John Smith

In [107]:
dff.drop(columns=['first', 'last'], inplace=True)

In [108]:
dff

               email         full_name
0            ben@xyz  Benjamin Rukundo
1           cory@xyz          Cory Doe
2  johndoe@email.com        John Smith

In [110]:
dff['full_name'].str.split(' ', expand=True)

          0        1
0  Benjamin  Rukundo
1      Cory      Doe
2      John    Smith

In [111]:
dff[['first', 'last']] = dff['full_name'].str.split(' ', expand=True)

In [112]:
dff

               email         full_name     first     last
0            ben@xyz  Benjamin Rukundo  Benjamin  Rukundo
1           cory@xyz          Cory Doe      Cory      Doe
2  johndoe@email.com        John Smith      John    Smith

In [114]:
dff.append({'first': 'Tony'}, ignore_index=True)

               email         full_name     first     last
0            ben@xyz  Benjamin Rukundo  Benjamin  Rukundo
1           cory@xyz          Cory Doe      Cory      Doe
2  johndoe@email.com        John Smith      John    Smith
3                NaN               NaN      Tony      NaN

In [116]:
people = {
    "first": ["Tony", "Steve"],
    "last": ["Stack", "Rogers"],
    "email": ["IronMan@avenge.com", "Cap@avenge.com"]
}
dff2 = pd.DataFrame(people)

In [117]:
dff2

   first    last               email
0   Tony   Stack  IronMan@avenge.com
1  Steve  Rogers      Cap@avenge.com

In [122]:
dff.append(dff2, ignore_index=True, sort=False)

                email         full_name     first     last
0             ben@xyz  Benjamin Rukundo  Benjamin  Rukundo
1            cory@xyz          Cory Doe      Cory      Doe
2   johndoe@email.com        John Smith      John    Smith
3  IronMan@avenge.com               NaN      Tony    Stack
4      Cap@avenge.com               NaN     Steve   Rogers

In [125]:
dff

               email         full_name     first     last
0            ben@xyz  Benjamin Rukundo  Benjamin  Rukundo
1           cory@xyz          Cory Doe      Cory      Doe
2  johndoe@email.com        John Smith      John    Smith

Sorting

In [127]:
dff.sort_values(by='last', ascending=False)

               email         full_name     first     last
2  johndoe@email.com        John Smith      John    Smith
0            ben@xyz  Benjamin Rukundo  Benjamin  Rukundo
1           cory@xyz          Cory Doe      Cory      Doe

In [129]:
dff.sort_values(by=['last', 'first'], ascending=False)

               email         full_name     first     last
2  johndoe@email.com        John Smith      John    Smith
0            ben@xyz  Benjamin Rukundo  Benjamin  Rukundo
1           cory@xyz          Cory Doe      Cory      Doe

In [131]:
dff.sort_values(by=['last', 'first'], ascending=[False, True], inplace=True)

In [132]:
dff

               email         full_name     first     last
2  johndoe@email.com        John Smith      John    Smith
0            ben@xyz  Benjamin Rukundo  Benjamin  Rukundo
1           cory@xyz          Cory Doe      Cory      Doe

In [133]:
dff.sort_index()

               email         full_name     first     last
0            ben@xyz  Benjamin Rukundo  Benjamin  Rukundo
1           cory@xyz          Cory Doe      Cory      Doe
2  johndoe@email.com        John Smith      John    Smith

In [134]:
dff['last'].sort_values()

1        Doe
0    Rukundo
2      Smith
Name: last, dtype: object

In [146]:
df.sort_values(by=['Country', 'ConvertedComp'], ascending=[True, False], inplace=True)

In [147]:
df[['Country', 'ConvertedComp']].head(50)

                Country  ConvertedComp
Respondent
50499       Afghanistan       153216.0
39258       Afghanistan        19152.0
7085        Afghanistan        14364.0
22450       Afghanistan         7980.0
48436       Afghanistan         4464.0
10746       Afghanistan         3996.0
8149        Afghanistan         1596.0
29736       Afghanistan         1116.0
722         Afghanistan            0.0
28638       Afghanistan            0.0
6417        Afghanistan            NaN
7353        Afghanistan            NaN
12310       Afghanistan            NaN
26340       Afghanistan            NaN
29045       Afghanistan            NaN
33178       Afghanistan            NaN
37802       Afghanistan            NaN
40000       Afghanistan            NaN
43106       Afghanistan            NaN
44403       Afghanistan            NaN
45854       Afghanistan            NaN
47110       Afghanistan            NaN
49702       Afghanistan            NaN
50767       Afghanistan            NaN
51859       Afghanistan            NaN
38308           Albania       187668.0
3787            Albania       114550.0
9270            Albania        74474.0
6716            Albania        60000.0
10303           Albania        57300.0
28873           Albania        34368.0
38928           Albania        24729.0
36574           Albania        23952.0
50326           Albania        23376.0
2332            Albania        22080.0
43878           Albania        20628.0
12265           Albania        18768.0
18295           Albania        13800.0
29164           Albania        13752.0
1954            Albania        11040.0
21700           Albania        11040.0
13385           Albania        10596.0
25100           Albania         9936.0
27637           Albania         9624.0
15993           Albania         8832.0
36028           Albania         8832.0
15374           Albania         7728.0
18869           Albania         7728.0
40830           Albania         7728.0
11549           Albania         6624.0

In [148]:
df['ConvertedComp'].nlargest(10)

Respondent
25983    2000000.0
22013    2000000.0
28243    2000000.0
52132    2000000.0
32250    2000000.0
58       2000000.0
102      2000000.0
166      2000000.0
436      2000000.0
452      2000000.0
Name: ConvertedComp, dtype: float64

In [150]:
df.nsmallest(10, 'ConvertedComp')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
722,I am a developer by profession,No,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,NaN,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,Less than 1 year,Younger than 5 years,Less than 1 year,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,NaN,No,NaN,I heard about a job opportunity (from a recrui...,AFN,Afghan afghani,1.0,Yearly,0.0,1.0,NaN,NaN,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",1.0,"No, and I'm glad we don't",NaN,I have little or no influence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,SIGH,What?,NaN,Neither,NaN,2008,Multiple times per day,NaN,More than 10 times per week,The other resource was much faster,60+ minutes,Not sure / can't remember,NaN,Yes,Yes,Not sure,Not applicable - I did not use Stack Overflow ...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Too long,Difficult
28638,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,NaN,NaN,NaN,36,13,16,Very dissatisfied,Very dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NaN,NaN,NaN,NaN,NaN,AFN,Afghan afghani,3.0,Monthly,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Java;Objective-C;O...,Bash/Shell/PowerShell;C;C++;Java;Objective-C;O...,MySQL;SQLite,MySQL;SQLite,Android;iOS;Linux;MacOS,Android;iOS;Linux,jQuery,NaN,TensorFlow;Unity 3D,Hadoop;TensorFlow;Unity 3D,Emacs,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,No,NaN,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,6-10 times per week,The other resource was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","No, not at all",A lot less welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN
13825,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,NaN,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,13,83,Less than 1 year,Very dissatisfied,Very satisfied,NaN,NaN,NaN,I am actively looking for a job,NA - I am an independent contractor or self em...,Complete a take-home project;Solve a brain-tea...,Yes,Financial performance or funding status of the...,"Something else changed (education, award, medi...",AFN,Afghan afghani,1.0,Yearly,0.0,168.0,NaN,Being tasked with non-development work;Non-wor...,About half the time,Home,Far above average,No,NaN,"Yes, it's part of our process",NaN,I have a great deal of influence,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,NaN,NaN,I do not use containers,NaN,An irresponsible use of resources,No,Yes,Yes,NaN,Neither,NaN,2015,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",A lot less welcome now than last year,NaN,56.0,NaN,NaN,NaN,NaN,Yes,Too short,Easy
40913,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Armenia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",2-9 employees,"Developer, desktop or enterprise applications;...",7,15,4,Slightly satisfied,Slightly satisfied,Very confident,Not sure,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",AMD,Armenian dram,0.0,Monthly,0.0,40.0,There's no schedule or spec; I work on what se...,"Meetings;Non-work commitments (parenting, scho...","Less than half the time, but at least one day ...",Office,A little above average,"Yes, because I see value in code review",3.0,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;C;C++;Java;JavaScript;Py...,C;C++;Java;Python;SQL;TypeScript,Elasticsearch;MariaDB;MongoDB;MySQL;Redis,MariaDB;MongoDB;MySQL,Arduino;AWS;Docker;Linux;MacOS;Raspberry Pi;Sl...,Arduino;Linux;MacOS;Raspberry Pi,ASP.NET;Django;Flask,Django;Flask,.NET;Node.js;TensorFlow;Torch/PyTorch,Node.js,IntelliJ;IPython / Jupyter;Sublime Text;Vim,Linux-based,Production,Not at all,A passing fad,No,SIGH,Yes,Facebook,In real life (in person),Username,2013,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers,22.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
30630,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,2-9 employees,"Database administrator;Developer, back-end;Dev...",35,7,30,Neither satisfied nor dissatisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self em...,Interview with people in peer roles;Interview ...,No,Industry that I'd be working in;Office environ...,I heard about a job opportunity (from a recrui...,AUD,Australian dollar,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what se...,Distracting work environment;Non-work commitme...,It's complicated,"Other place, such as a coworking space or cafe",A little above average,"Yes, because I see value in code review",10.0,"No, but I think we should",NaN,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Ruby,Elixir;Ruby;TypeScript,PostgreSQL,PostgreSQL,AWS;iOS,Android;AWS;iOS,Ruby on Rails;Vue.js,Ruby on Rails;Vue.js,Chef;React Native,React Native,Sublime Text;TextMate;Vim;Xcode,MacOS,I do not use containers,Not at all,An irresponsible use of resources,Yes,"Fortunately, someone else has that title",No,Reddit,Online,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",A lot less welcome now than last year,NaN,43.0,NaN,No,NaN,NaN,No,Appropriate in length,Easy
19340,"I am not primarily a developer, but I write co...",Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",NaN,Austria,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Fine arts or performing arts (ex. graphic desi...,Taken an online course in programming or softw...,NaN,NaN,10,20,5,Neither satisfied nor dissatisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",3-4 years ago,Interview with people in peer roles;Interview ...,No,Office environment or company culture;Opportun...,I was preparing for a job search,CHF,Swiss franc,0.0,Monthly,0.0,35.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,Average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have a great deal of influence,Assembly;C;Elixir;HTML/CSS;Java;JavaScript;Pyt...,Clojure,PostgreSQL;SQLite,NaN,Arduino;Raspberry Pi,Arduino;Raspberry Pi,Other(s):,Other(s):,NaN,NaN,IntelliJ;Sublime Text,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful for immutable record keeping outside of...,No,Also Yes,Yes,NaN,In real life (in person),Username,2010,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,NaN,32.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
16214,"I am not primarily a developer, but I write co...",Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",NaN,20 to 99 employees,"Engineer, data;Engineering manager;Product man...",20,16,20,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Interview with people in peer roles,No,Financial performance or funding status of the...,I was preparing for a job search,EUR,European Euro,0.0,Yearly,0.0,10.0,There's no schedule or spec; I work on what se...,Lack of support from management;Meetings;Time ...,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,No,NaN,"No, and I'm glad we don't",Developers and management have nearly equal in...,I have a great deal of influence,Java;PHP;Other(s):,Java;PHP;Other(s):,MariaDB;MySQL,MariaDB;MySQL,Android;Linux;Raspberry Pi;Windows;WordPress,Android;Linux;Raspberry Pi;Windows;WordPress,jQuery;Spring,jQuery;Spring,NaN,NaN,Android Studio;Eclipse;IntelliJ;NetBeans,Linux-based,I do not use containers,Not at all,NaN,No,Yes,What?,WhatsApp,Neither,NaN,2008,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,99.0,NaN,No,NaN,NaN,NaN,Too long,Easy
29355,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",Bosnia and Herzegovina,"Yes, part-time",Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","Just me - I am a freelancer, sole proprietor, ...",NaN,10,10,6,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,Less than a year ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Specific depar...,"Something else changed (education, award, medi...",BAM,Bosnia and Herzegovina convertible mark,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Inadequ...,It's complicated,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",20.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Python;Ruby;Other(s):,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;Oth...,NaN,NaN,Linux;MacOS;Microsoft Azure;Raspberry Pi;Windows,Android;Arduino;AWS;iOS;Linux;MacOS;Raspberry ...,NaN,NaN,Pandas;TensorFlow;Torch/PyTorch;Unity 3D;Unrea...,.NET;Torch/PyTorch;Unity 3D,Android Studio;Emacs;PyCharm;Visual Studio;Vis...,Linux-based,I do not use containers,NaN,A passing fad,Yes,Also Yes,Yes,YouTube,In real life (in person),Username,2013,A few times per month or weekly,Find answers to specific questions;Learn how t...,Less than once per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,NaN,No,NaN,NaN,NaN,Too long,Easy
1685,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",Brazil,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...","Designer;Developer, full-stack;Developer, game...",8,16,3,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,Specific department or team I'd be working on;...,I was preparing for a job search,BRL,Brazilian real,0.0,Monthly,0.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Toxic wo...,All or almost all the time (I'm full-time remote),Home,Average,"Yes, because I see value in code review",6.0,NaN,NaN,NaN,Elixir;HTML/CSS;JavaScript;PHP;Python,C#;Kotlin;Python,Cassandra;MariaDB;MongoDB;PostgreSQL,Cassandra;MariaDB;MongoDB;PostgreSQL,Docker;Kubernetes;MacOS,Android;Linux;Windows,Laravel,Django;Flask;Laravel;Vue.js,Node.js,.NET;Node.js;Unity 3D;Other(s):,Android Studio;PHPStorm;PyCharm;Visual Studio ...,Windows,Development,NaN,Useful across many domains and could change ma...,No,Yes,Yes,WhatsApp,In real life (in person),NaN,2010,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Neither easy nor difficult
11875,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Brazil,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees",Data or business analyst;Data scientist or mac...,29,11,24,Neither satisfied nor dissatisfied,Very dissatisfied,Not at all confident,Yes,No,I am actively looking for a job,3-4 years ago,Write any code;Complete a take-home project;In...,Yes,Office environment or company culture;Opportun...,I was preparing for a job search,BRL,Brazilian real,0.0,Weekly,0.0,48.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",4.0,"Yes, it's not part of our process but the deve...",Not sure,I have little or no influence,C#;HTML/CSS;Java;JavaScript;Python;SQL,C#;Python;SQL,Microsoft SQL Server;Oracle;PostgreSQL;SQLite,Elasticsearch;Microsoft SQL Server;Oracle;Post...,Docker;Heroku;Linux;Microsoft Azure;Windows;Ot...,Docker;Heroku;Linux;Microsoft Azure;Windows;Ot...,ASP.NET;jQuery,ASP.NET;Django;Flask;Vue.js,.NET;.NET Core,Hadoop;.NET;.NET Core;Pandas;TensorFlow;Torch/...,Notepad++;Visual Studio;Visual Studio Code,Windows,Development,NaN,Useful for immutable record keeping outside of...,No,SIGH,Yes,I don't use social media,In real life (in person),Login,2008,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,Yes,"Yes, somewhat",Just as welcome now as I felt last year,NaN,40.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy

In [151]:
df['ConvertedComp'].median()

57287.0

In [152]:
df.median()

<ipython-input-152-6d467abf240d>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median()

CompTotal        61750.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [153]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  3.373900e+04   3.366100e+04  38966.000000  30063.000000  47715.000000
mean   9.151387e+11   1.270980e+05     42.209996      5.114335     30.359459
std    9.441197e+13   2.831694e+05     36.988740      5.601836      9.171897
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.584800e+04     40.000000      2.000000     24.000000
50%    6.175000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.000000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4125.000000     99.000000     99.000000

In [154]:
df['ConvertedComp'].count()

33661

In [155]:
df['Hobbyist']

Respondent
50499    Yes
39258    Yes
7085     Yes
22450     No
48436     No
        ...
32960    Yes
48100    Yes
51356     No
51464    Yes
53047    Yes
Name: Hobbyist, Length: 53412, dtype: object

In [156]:
df['Hobbyist'].value_counts()

Yes    42862
No     10550
Name: Hobbyist, dtype: int64

In [157]:
df['SocialMedia']

Respondent
50499     WhatsApp
39258     Facebook
7085     Instagram
22450     Facebook
48436     Facebook
           ...
32960     WhatsApp
48100      YouTube
51356     Facebook
51464     WhatsApp
53047     LinkedIn
Name: SocialMedia, Length: 53412, dtype: object

In [158]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [161]:
df['SocialMedia'].value_counts(normalize=True)

Reddit                      0.172837
YouTube                     0.162029
WhatsApp                    0.158492
Facebook                    0.155506
Twitter                     0.136446
Instagram                   0.073489
I don't use social media    0.065983
LinkedIn                    0.052032
WeChat 微信                   0.007860
Snapchat                    0.007231
VK ВКонта́кте               0.006858
Weibo 新浪微博                  0.000707
Youku Tudou 优酷              0.000295
Hello                       0.000236
Name: SocialMedia, dtype: float64

Grouping Data

In [162]:
df['Country'].value_counts()

United States     12582
India              5478
Germany            3505
United Kingdom     3447
Canada             2021
                  ...
North Korea           1
Niger                 1
Malawi                1
Mali                  1
Liberia               1
Name: Country, Length: 175, dtype: int64

In [164]:
country_grp = df.groupby(['Country'])

In [166]:
country_grp.get_group('India')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
22013,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,2-9 employees,Academic researcher;Data scientist or machine ...,3,26,3,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,"Write code by hand (e.g., on a whiteboard);Com...",No,Financial performance or funding status of the...,"Something else changed (education, award, medi...",USD,United States dollar,1500000.0,Weekly,2000000.0,50.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Meetings;...,All or almost all the time (I'm full-time remote),Home,A little below average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have a great deal of influence,Assembly;Bash/Shell/PowerShell;C;C++;Java;Java...,Python;Swift,Cassandra;Microsoft SQL Server;Oracle,Cassandra,Android;Arduino;Google Cloud Platform;IBM Clou...,IBM Cloud or Watson;Windows,jQuery,NaN,TensorFlow,TensorFlow,Visual Studio;Visual Studio Code,Windows,Development,Implementing our own cryptocurrency,Useful across many domains and could change ma...,Yes,Yes,No,YouTube,Online,Screen Name,NaN,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,Yes,"Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28243,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Developer, back-end;Developer, full-stack;Deve...",25,9,14,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles;Interview ...,Yes,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,USD,United States dollar,2000000.0,Yearly,2000000.0,20.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Not eno...,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",NaN,NaN,NaN,NaN,C++;C#;Java;JavaScript;Objective-C;Python,C;C++;C#,PostgreSQL;SQLite,SQLite,Android;AWS;iOS;MacOS;Windows,Android;Linux,NaN,NaN,Node.js;Pandas;Unity 3D,Unity 3D;Unreal Engine,Android Studio;Coda;PyCharm;Visual Studio;Visu...,MacOS,I do not use containers,NaN,An irresponsible use of resources,No,Yes,No,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,Multiple times per day,Yes,"No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
16793,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher;Data or business analyst;D...,14,14,6,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am actively looking for a job,1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Opportun...,I heard about a job opportunity (from a recrui...,INR,Indian rupee,106673250.0,Yearly,1000000.0,50.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Non-work commitme...,It's complicated,Office,Far above average,"Yes, because I see value in code review",20.0,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;C#;Dart;G...,Bash/Shell/PowerShell;C;C++;Go;HTML/CSS;Java;J...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Angular/Angular.js;ASP.NET;Django;Drupal;Expre...,Angular/Angular.js;ASP.NET;Django;Flask;jQuery...,Apache Spark;Flutter;Hadoop;.NET;.NET Core;Nod...,Apache Spark;Hadoop;Pandas;TensorFlow;Torch/Py...,Android Studio;Atom;Eclipse;Emacs;IntelliJ;IPy...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,Also Yes,What?,LinkedIn,Online,Handle,2009,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,27.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
52561,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"5,000 to 9,999 employees","Developer, back-end;Developer, desktop or ente...",12,11,9,Slightly satisfied,Slightly satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",INR,Indian rupee,2000000.0,Weekly,1000000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Distrac...,A few days each month,Office,A little above average,"Yes, because I was told to do so",2.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have some influence,C#;JavaScript,C#;JavaScript,DynamoDB;Microsoft SQL Server;SQLite,DynamoDB;Microsoft SQL Server,AWS;Docker;Linux;Windows,AWS;Docker;Linux;Windows,Angular/Angular.js;ASP.NET;Express;React.js,Angular/Angular.js;ASP.NET;Express;React.js,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js,Visual Studio;Visual Studio Code,Windows,Development;Testing;Production;Outside of work...,Not at all,Useful for immutable record keeping outside of...,No,Also Yes,Yes,YouTube,Online,UserID,2009,Daily or almost daily,Find answers to specific questions;Contribute ...,1-2 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,31.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Easy
32536,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Database administrator;Developer, back-end;Sen...",14,7,7,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am actively looking for a job,Less than a year ago,Interview with people in senior / management r...,No,Office environment or company culture;Opportun...,I was preparing for a job search,INR,Indian rupee,43000000.0,Yearly,601690.0,30.0,NaN,Being tasked with non-development work;Meeting...,A few days each month,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's not part of our process but the deve...",NaN,I have a great deal of influence,C++;Java;JavaScript;Python;SQL,C++;Java;Kotlin;Python;SQL,Cassandra;Elasticsearch;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,AWS,AWS,Flask;Spring,Django;Flask;React.js;Spring,Ansible;Apache Spark;Node.js,Ansible;Apache Spark;Hadoop;Node.js;Pandas;Rea...,IntelliJ;IPython / Jupyter;Vim,MacOS,"Outside of work, for personal projects",Not at all,A passing fad,Yes,Yes,Yes,WhatsApp,Online,Handle,2008,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,The other resource was slightly faster,0-10 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,32.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53640,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,10 to 19 employees,"Developer, full-stack",8,17,4,Very satisfied,Slightly satisfied,Not at all confident,Yes,I am already a manager,"I’m not actively looking, but I am open to new...",3-4 years ago,"Write code by hand (e.g., on a whiteboard);Com...",Yes,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",INR,Indian rupee,NaN,NaN,NaN,60.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",20.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have a great deal of influence,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,MySQL;Other(s):,Cassandra;Elasticsearch;MySQL;Other(s):,AWS;Microsoft Azure;Slack;Windows;WordPress,AWS;Google Cloud Platform;IBM Cloud or Watson;...,Angular/Angular.js;Express;jQuery;Spring,Angular/Angular.js;Express;jQuery;Spring;Vue.js,Node.js,Ansible;Node.js;TensorFlow,Atom;Eclipse;PyCharm;Sublime Text;Vim;Visual S...,Windows,I do not use containers,Not at all,A passing fad,No,Yes,Yes,LinkedIn,In real life (in person),UserID,2012,Multiple times per day,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Daily or almost daily,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,25.0,Man,No,Straight / Heterosexual,South Asian,No,Too long,Easy
53698,I am a developer by profession,No,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,"Developer, back-end;Developer, front-end;Devel...",10,18,6,Slightly satisfied,Slightly dissatisfied,Not at all confident,Yes,Yes,I am actively looking for a job,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,INR,Indian rupee,NaN,NaN,NaN,NaN,There is a schedule and/or spec (made by me or...,Being tasked with non-development work,Less than once per month / Never,Office,Average,"Yes, because I was told to do so",10.0,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,HTML/CSS;JavaScript;PHP,HTML/CSS;JavaScript;PHP,PostgreSQL,MongoDB;PostgreSQL;Redis,Windows,AWS;Windows,NaN,React.js,NaN,NaN,Notepad++;PHPStorm,Windows,I do not use containers,NaN,NaN,Yes,SIGH,What?,Instagram,In real life (in person),Screen Name,2015,Multiple times per day,Find answers to specific questions;Contribute ...,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,29.0,Man,No,NaN,South Asian,Yes,Appropriate in length,Easy
53701,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Engineer, data;Student",2,19,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,I heard about a job opportunity (from a recrui...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;Java,Java;Python;SQL,NaN,MySQL,Arduino;Raspberry Pi,Android;Arduino;Raspberry Pi,Django,Django;Ruby on Rails,.NET,.NET,Android Studio;Eclipse;NetBeans;Notepad++,Windows,Testing,NaN,"Useful for decentralized currency (i.e., Bitcoin)",No,Also Yes,No,Instagram,Online,Username,2017,Less than once per month or monthly,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Courses on technologies you're interested in,21.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
53716,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, front-end;Developer, full-stack;Dev...",6,16,1,Very satisfied,Slightly dissatisfied,Very confident,Yes,Not sure,"I’m not actively looking, but I am open to new...",I've never had a job,"Write any code;Write code by hand (e.g., on a ...",No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",INR,Indian rupee,NaN,Monthly,NaN,10.0,There is a schedule and/or spec (made by me or...,Inadequate access to necessary tools;Lack of s...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",4.0,"No, but I think we should",Not sure,I have some influence,Java;JavaScript,JavaScript;Python,Firebase,Firebase;MongoDB,Android;Other(s):,Android;AWS;Other(s):,React.js,React.js,Pandas;React Native;TensorFlow;Unity 3D,Node.js;Pandas;React Native;TensorFlow,Android Studio;Visual Studio Code,Windows,NaN,NaN,Useful for immutable record keeping outside of...,Yes,Also Yes,No,LinkedIn,In real life (in person),Login,2017,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,The other resource was slightly faster,60+ minutes,Yes,A few times per week,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
53717,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,NaN,"Developer, back-end;Developer, front-end",4,21,3,Neither satisfied nor dissatisfied,Slightly dissatisfied,Very confident,Yes,Yes,"I’m not actively looking, but I am open to new...",Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",Yes,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,NaN,Yearly,NaN,8.0,There is a schedule and/or spec (made by me or...,Meetings;Not enough people for the workload;Ti...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",4.0,"No, but I think we should",Not sure,NaN,C#;HTML/CSS;JavaScript;SQL;Other(s):,C#;HTML/CSS;JavaScript;Python;SQL;TypeScript;O...,MySQL,MongoDB;MySQL,Microsoft Azure;Windows,Microsoft Azure;Windows,ASP.NET;jQuery,jQuery,.NET;.NET Core,.NET;.NET Core;Node.js;Xamarin,Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,NaN,No,SIGH,What?,Instagram,In real life (in person),Login,2015,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was much faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Woman,NaN,NaN,NaN,No,Too long,Easy

In [169]:
filt = df['Country'] == 'United States'
df.loc[filt]['SocialMedia'].value_counts()

Reddit                      3521
Twitter                     2116
Facebook                    1695
YouTube                     1443
I don't use social media    1100
Instagram                    981
LinkedIn                     589
WhatsApp                     363
Snapchat                     184
WeChat 微信                     55
Weibo 新浪微博                     7
VK ВКонта́кте                  5
Youku Tudou 优酷                 1
Name: SocialMedia, dtype: int64

In [176]:
country_grp['SocialMedia'].value_counts(normalize=True).loc['China']

SocialMedia
WeChat 微信                   0.680000
YouTube                     0.090667
Weibo 新浪微博                  0.066667
Twitter                     0.042667
I don't use social media    0.040000
Reddit                      0.024000
LinkedIn                    0.018667
Instagram                   0.010667
Youku Tudou 优酷              0.010667
Facebook                    0.008000
WhatsApp                    0.005333
VK ВКонта́кте               0.002667
Name: SocialMedia, dtype: float64

In [178]:
country_grp['ConvertedComp'].median().loc['Germany']

61872.0

In [180]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     69468.000000
mean      134770.280443
Name: Canada, dtype: float64

In [184]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('python').sum()

0

In [185]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                              3
Albania                                 16
Algeria                                 16
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    19
Viet Nam                                54
Yemen                                    2
Zambia                                   1
Zimbabwe                                11
Name: LanguageWorkedWith, Length: 175, dtype: int64

In [186]:
country_respondents = df['Country'].value_counts()
country_respondents

United States     12582
India              5478
Germany            3505
United Kingdom     3447
Canada             2021
                  ...
North Korea           1
Niger                 1
Malawi                1
Mali                  1
Liberia               1
Name: Country, Length: 175, dtype: int64

In [187]:
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              3
Albania                                 16
Algeria                                 16
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    19
Viet Nam                                54
Yemen                                    2
Zambia                                   1
Zimbabwe                                11
Name: LanguageWorkedWith, Length: 175, dtype: int64

In [189]:
python_df = pd.concat([country_respondents, country_uses_python], axis='columns', sort=False)
python_df

                Country  LanguageWorkedWith
United States     12582                6037
India              5478                1863
Germany            3505                1465
United Kingdom     3447                1415
Canada             2021                 939
...                 ...                 ...
North Korea           1                   0
Niger                 1                   1
Malawi                1                   0
Mali                  1                   1
Liberia               1                   0

[175 rows x 2 columns]

In [195]:
python_df.rename(columns={'Country': 'NumRespondents', 'LanguageWorkedWith': 'NumKnowsPython'}, inplace=True)

In [196]:
python_df

                NumRespondents  NumKnowsPython
United States            12582            6037
India                     5478            1863
Germany                   3505            1465
United Kingdom            3447            1415
Canada                    2021             939
...                        ...             ...
North Korea                  1               0
Niger                        1               1
Malawi                       1               0
Mali                         1               1
Liberia                      1               0

[175 rows x 2 columns]

In [197]:
python_df['PctKnowsPython'] = (python_df['NumKnowsPython']/python_df['NumRespondents']) * 100
python_df

                NumRespondents  NumKnowsPython  PctKnowsPython
United States            12582            6037       47.981243
India                     5478            1863       34.008762
Germany                   3505            1465       41.797432
United Kingdom            3447            1415       41.050189
Canada                    2021             939       46.462147
...                        ...             ...             ...
North Korea                  1               0        0.000000
Niger                        1               1      100.000000
Malawi                       1               0        0.000000
Mali                         1               1      100.000000
Liberia                      1               0        0.000000

[175 rows x 3 columns]

In [199]:
python_df.sort_values(by='PctKnowsPython', ascending=False, inplace=True)

NB: inplace helps to put the necessary change inplace on the dataframe

In [201]:
python_df.head(50)

                             NumRespondents  NumKnowsPython  PctKnowsPython
Dominica                                  1               1      100.000000
Mali                                      1               1      100.000000
Niger                                     1               1      100.000000
Timor-Leste                               1               1      100.000000
Turkmenistan                              6               5       83.333333
Congo, Republic of the...                 5               4       80.000000
Benin                                     4               3       75.000000
Uganda                                   38              26       68.421053
Guinea                                    3               2       66.666667
Oman                                      6               4       66.666667
Bahamas                                   3               2       66.666667
Angola                                    3               2       66.666667
Guyana                                    3               2       66.666667
Namibia                                   5               3       60.000000
Iceland                                  31              18       58.064516
Finland                                 337             173       51.335312
Maldives                                  6               3       50.000000
Haiti                                     4               2       50.000000
Ethiopia                                 30              15       50.000000
Mauritania                                4               2       50.000000
Republic of Korea                        26              13       50.000000
Monaco                                    2               1       50.000000
United Republic of Tanzania              18               9       50.000000
Iraq                                     18               9       50.000000
Uzbekistan                               16               8       50.000000
Mongolia                                 12               6       50.000000
Bhutan                                    2               1       50.000000
Liechtenstein                             2               1       50.000000
Sierra Leone                              2               1       50.000000
South Korea                              91              45       49.450549
Taiwan                                  116              57       49.137931
Ecuador                                  54              26       48.148148
United States                         12582            6037       47.981243
Cuba                                     17               8       47.058824
Japan                                   228             107       46.929825
China                                   416             195       46.875000
Chile                                   126              59       46.825397
Israel                                  569             266       46.748682
Canada                                 2021             939       46.462147
Switzerland                             597             277       46.398660
Luxembourg                               37              17       45.945946
Hong Kong (S.A.R.)                      114              52       45.614035
Nepal                                   140              63       45.000000
France                                 1449             648       44.720497
Kenya                                   147              65       44.217687
Estonia                                 105              46       43.809524
Panama                                   16               7       43.750000
Thailand                                126              55       43.650794
Austria                                 499             214       42.885772
Netherlands                            1103             473       42.883046

In [202]:
python_df.loc['Japan']

NumRespondents    228.000000
NumKnowsPython    107.000000
PctKnowsPython     46.929825
Name: Japan, dtype: float64